server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: a
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    zookeeper:
      connect-string: localhost:2181
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
logging:
  level:
    com.yc.springcloud81.misprovider.dao: debug